export const userImages = {
  visinoskij: "/assets/visinoskij.jpg",
  miso: "/assets/miso.jpg",
  carlo: "/assets/carlo.jpg",
  evilloh: "/assets/evilloh.jpg",
  matteo: "/assets/matteo.jpg",
  pezzo: "/assets/pezzo.jpg",
  pezzo2: "/assets/pezzo2.jpg",
  nata: "/assets/nata.jpg",
  rosy: "/assets/rosy.jpg",
  pinottopoppo: "/assets/pinottopoppo.jpg",
  pinottodos: "/assets/pinottopoppo.jpg",
  sonrisitas: "/assets/sonrisitasavatar.png",
  felipe: "/assets/felipe.jpg",
  dia: "/assets/dia.png",
  nit: "/assets/nit.png",
  bigolo: "/assets/bigolo.png",
};
